### ISSUE TITLE
Omitting displayName outputs "Unknown" instead of capitalised modId

### ISSUE THREAD

**Issue by PaintNinja** [GroovyMC/ModsDotGroovy#7]
My mods.groovy:

```groovy
ModsDotGroovy.make {
    modLoader = 'gml'
    loaderVersion = '[1,)'

    license = 'MIT'
    issueTrackerUrl = 'https://github.com/PaintNinja/Groovylicious/issues'

    mod {
        modId = 'groovylicious'
        version = this.version

        displayUrl = 'https://www.curseforge.com/minecraft/mc-mods/Groovylicious'
        description = 'Delicious syntax sugar with the power of Groovy!'
        authors = ['Paint_Ninja', 'Matyrobbrt']

        logoFile = 'logo.png'

        dependencies {
            // The `forgeVersion` and `minecraftVersion` properties are computed from the `minecraft` dependency in the `build.gradle` file
            forge = "[${this.forgeVersion},)"
            // The automatically generated `minecraftVersionRange` property is computed as: [1.$minecraftMajorVersion,1.${minecraftMajorVersion + 1})
            // Example: for a Minecraft version of 1.19, the computed `minecraftVersionRange` is [1.19,1.20)
            minecraft = this.minecraftVersionRange
        }
    }
}
```
Note that the displayName is omitted.

The mods.toml output:
```toml
modLoader = "gml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/PaintNinja/Groovylicious/issues"

[[mods]]
  modId = "groovylicious"
  version = "1.19.2-0.2.0-SNAPSHOT"
  displayName = "Unknown"
  displayUrl = "https://www.curseforge.com/minecraft/mc-mods/Groovylicious"
  logoFile = "logo.png"
  description = "Delicious syntax sugar with the power of Groovy!"
  authors = "Paint_Ninja and Matyrobbrt"

    [[dependencies.groovylicious]]
      mandatory = true
      versionRange = "[1.19.2,1.20)"
      ordering = "NONE"
      side = "BOTH"
      modId = "minecraft"

    [[dependencies.groovylicious]]
      mandatory = true
      versionRange = "[43.1.3,)"
      ordering = "NONE"
      side = "BOTH"
      modId = "forge"
```

The expected behaviour: for the displayName to become the capitalised modId ("Groovylicious" in this case). https://github.com/GroovyMC/ModsDotGroovy/blob/master/src/lib/groovy/modsdotgroovy/ModInfoBuilder.groovy#L46

Current behaviour: the displayName becomes "Unknown"
